services:
  - type: web
    name: ev-spots-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
    healthCheckPath: / 